apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-github-actions
        image: 767397705569.dkr.ecr.us-east-1.amazonaws.com/nodejs-github-action:v1
        ports:
        - containerPort: 80
